#!/usr/bin/env bun
/**
 * Generates TypeScript definitions from Arrow Flight SQL proto files.
 *
 * This script downloads the official proto files from the Apache Arrow repository
 * and generates TypeScript types using @grpc/proto-loader.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const currentDir = dirname(fileURLToPath(import.meta.url))
const protoDir = join(currentDir, "..", "proto")
const generatedDir = join(currentDir, "..", "src", "generated")

// Apache Arrow proto files - pinned to a stable release
const arrowVersion = "apache-arrow-19.0.0"
const protoBaseUrl = `https://raw.githubusercontent.com/apache/arrow/${arrowVersion}/format`

const protoFiles = [
  { name: "Flight.proto", url: `${protoBaseUrl}/Flight.proto` },
  { name: "FlightSql.proto", url: `${protoBaseUrl}/FlightSql.proto` }
]

async function downloadProtoFiles(): Promise<void> {
  if (!existsSync(protoDir)) {
    mkdirSync(protoDir, { recursive: true })
  }

  console.log(`Downloading proto files from Arrow ${arrowVersion}...`)

  for (const file of protoFiles) {
    const response = await fetch(file.url)
    if (!response.ok) {
      throw new Error(`Failed to download ${file.name}: ${response.statusText}`)
    }
    const content = await response.text()
    const filePath = join(protoDir, file.name)
    writeFileSync(filePath, content)
    console.log(`  ✓ ${file.name}`)
  }
}

function generateTypeDefinitions(): void {
  if (!existsSync(generatedDir)) {
    mkdirSync(generatedDir, { recursive: true })
  }

  console.log("\nGenerating TypeScript definitions...")

  // Use proto-loader to load and generate types at build time
  // The actual gRPC service definitions will be loaded dynamically at runtime
  const indexContent = `// Auto-generated by scripts/generate-proto.ts
// Do not edit manually

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import * as grpc from "@grpc/grpc-js";
import * as protoLoader from "@grpc/proto-loader";

const currentDir = dirname(fileURLToPath(import.meta.url));
const protoDir = join(currentDir, "..", "..", "proto");

const protoLoaderOptions: protoLoader.Options = {
  keepCase: false,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true,
  includeDirs: [protoDir],
};

let flightServiceDefinitionCache: grpc.GrpcObject | null = null;
let flightSqlServiceDefinitionCache: grpc.GrpcObject | null = null;

export async function getFlightServiceDefinition(): Promise<grpc.GrpcObject> {
  if (!flightServiceDefinitionCache) {
    const packageDefinition = await protoLoader.load(
      join(protoDir, "Flight.proto"),
      protoLoaderOptions
    );
    flightServiceDefinitionCache = grpc.loadPackageDefinition(packageDefinition);
  }
  return flightServiceDefinitionCache;
}

export async function getFlightSqlServiceDefinition(): Promise<grpc.GrpcObject> {
  if (!flightSqlServiceDefinitionCache) {
    const packageDefinition = await protoLoader.load(
      join(protoDir, "FlightSql.proto"),
      protoLoaderOptions
    );
    flightSqlServiceDefinitionCache = grpc.loadPackageDefinition(packageDefinition);
  }
  return flightSqlServiceDefinitionCache;
}
`

  writeFileSync(join(generatedDir, "index.ts"), indexContent)
  console.log("  ✓ src/generated/index.ts")
}

async function main(): Promise<void> {
  console.log("Arrow Flight SQL Proto Generator\n")

  try {
    await downloadProtoFiles()
    generateTypeDefinitions()
    console.log("\n✓ Proto generation complete!")
  } catch (error) {
    console.error("\n✗ Proto generation failed:", error)
    process.exit(1)
  }
}

void main()
